export const REF_STORAGE_THRESHOLD_CHARS = 12_000;
export const COMPACT_PREVIEW_MAX_CHARS = 240;
export const COMPACT_PREVIEW_MAX_LINES = 3;
export const COMPACT_PREVIEW_MAX_ITEMS = 4;
export const FULLSCREEN_CHUNK_PREVIEW_MAX_CHARS = 16_000;
export const FULLSCREEN_CHUNK_PREVIEW_MAX_LINES = 200;
export const FULL_RENDER_SAFE_THRESHOLD_CHARS = 100_000;
